baseURL = "https://jamstackthemes.dev"
languageCode = "en-us"
title = "JAMstack Themes"
theme = "jamstackthemes"
# paginate = 30
# enableGitInfo = true

[params]
  google_analytics_id = ""
  description = "A list of Themes and Starters for JAMstack Sites."
  banner = true
  banner_fixed = true
  banner_text = "Announcing the Stackbit Control Center for managing modern websites. ğŸ¤™ğŸ‘©ğŸ¼â€ğŸ¤ğŸ”¥"
  banner_link = "https://www.stackbit.com/control-center/"
  banner_link_text = "Try It Now"
 
[taxonomies]
  ssg = "ssg"
  cms = "cms"
  css = "css"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]

# Main Menu
# [[menu.main]]
# 	name = "About"
# 	url = "/about/"
#     weight = 1
