baseURL = "/"
languageCode = "en-us"
title = "JAMStack Themes"
theme = "jamstackthemes"
paginate = 3
enableGitInfo = true

[taxonomies]
  ssg =  "ssg"
  cms = "cms"
  css = "css"

[params]
    google_analytics_id = "UA-122379868-3"

[outputs]
  home = ["HTML","RSS","JSON"]
  section = ["HTML","RSS"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime", ":default"]


# Main Menu
[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1
